worker_processes 1;
events { worker_connections 1024; }

http {
    lua_package_path "/usr/local/openresty/nginx/conf/?.lua;;";

    lua_shared_dict rif_store 1m;
    lua_shared_dict peers 1m;

    resolver 127.0.0.11 ipv6=off;

    init_worker_by_lua_block {
        require("p2c").init_peers({
            "nginx-thrift-1:8080",
            "nginx-thrift-2:8080",
            "nginx-thrift-3:8080",
            "nginx-thrift-4:8080",
        })
    }

    server {
        listen 80;
        set $backend "";
        error_log stderr notice;
        access_log off;
        location / {
            access_by_lua_block { require("p2c").choose_backend() }
            proxy_pass $backend$request_uri;
            proxy_set_header Host $host;
            log_by_lua_block { require("p2c").finish_request() }
        }
    }
}
