worker_processes  1;
error_log  stderr notice;


events { worker_connections 1024; }

http {
    lua_package_path "/usr/local/openresty/nginx/conf/?.lua;;";

    # Shared state for Lua
    lua_shared_dict rif_store  1m;   # per-backend in-flight counters
    lua_shared_dict rtt_store  5m;   # recent latency samples
    lua_shared_dict q_stats    128k; # quantiles / hot-cold book-keeping

    # List of back-end replicas
    lua_shared_dict peers 1m;  # immutable, filled in init_worker_by_lua*

    # ─── Docker DNS + alias ─────────────────────────────
    resolver 127.0.0.11 ipv6=off;

    init_worker_by_lua_block {
        require("prequal").init_peers({
            "nginx-thrift-1:8080",
            "nginx-thrift-2:8080",
            "nginx-thrift-3:8080",
            "nginx-thrift-4:8080",
        })
    }

    server {
        listen 80;
        error_log stderr notice;
        access_log off;
        set $backend '';

        # choose backend & proxy
        location / {
            access_by_lua_block   { require("prequal").choose_backend() }
            proxy_pass $backend$request_uri;   # set by Lua
            proxy_set_header      Host $host;
            header_filter_by_lua_block {
                require("prequal").note_latency()
            }
            log_by_lua_block      { require("prequal").finish_request() }
        }
    }
}
