worker_processes auto;
events {
    worker_connections 8192;
    multi_accept on;
    use epoll;
}

http {
    resolver 127.0.0.11 ipv6=off;

    upstream backend_servers {
        server nginx-thrift-1:8080;
        server nginx-thrift-2:8080;
        server nginx-thrift-3:8080;
        server nginx-thrift-4:8080;
    }

    server {
        listen 80;
        error_log stderr notice;
        access_log off;

        location / {
            proxy_pass http://backend_servers$request_uri;
            proxy_set_header Host $host;
        }
    }
}
